version: '3'
services:
  apisix:
    image: apache/apisix:2.14.1-alpine
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/routes.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
      - "9090:9090"
  catalog:
    build: ./catalog
    ports:
      - "5001:5001"
  news:
    build: ./news
    ports:
      - "5002:5002"
